package com.example.mapper;

import com.example.DTO.TransactionRequestDTO;
import com.example.DTO.TransactionResponseDTO;
import com.example.entities.Transaction;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface TransactionMapper {
    @Mapping(target = "transactionId", ignore = true) // ID will be auto-generated by JPA
    Transaction toEntity(TransactionRequestDTO dto);

    @Mapping(source = "account.accountName", target = "accountName")
    @Mapping(source = "category.categoryName", target = "categoryName")
    TransactionResponseDTO toDTO(Transaction transaction);
}
